### ISSUE TITLE
Is there an update to the latest Vaadin version?

### ISSUE THREAD

**Issue by madukan** [vaadin-learning-center/crm-tutorial#171]
I see some issues when using the latest Vaadin version. Especially around that Oracle vs Eclipse branding changes as well.

**Comment by Legioth** [comment]
The default branch in this repository, `v24` is based on the Vaadin 24 which in turn is based on Jakarta EE rather than Java EE.

Here's an example from the latest version right now, where the import for a JPA entity is `jakarta.persistence.Entity`:

https://github.com/vaadin/flow-crm-tutorial/blob/756c650861332fa311982b13dce8554a0508d48e/src/main/java/com/example/application/data/entity/Status.java#L1-L6

Could you describe exactly what issues you're seeing?

**Comment by madukan** [comment]
Right. Thank you. I can see in the v24, Jakarta, is being used. It works fine now.
